"""Sprint 2: turn everything in data/raw/ into one clean, deduplicated,
anonymized corpus ready for stratified annotation sampling.

    python -m src.preprocess.build_corpus
    python -m src.preprocess.build_corpus --exclude kids_gaming.jsonl

Outputs (all gitignored - they still derive from raw YouTube data):
    data/interim/corpus_clean.jsonl      the annotatable pool, one record per comment
    data/interim/corpus_romanized.jsonl  Latin-script comments, held aside
    data/interim/corpus_otherlang.jsonl  Kyrgyz / Uzbek / Ukrainian, held aside
    data/interim/corpus_report.md        what was dropped and why, for the report

Unlike make_pilot.py this does NOT sample - it produces the whole pool. Sampling
is a separate, documented decision: see make_batches.py and docs/sampling_design.md.

Every record carries the screen bucket, but the screen is a SAMPLING tool with
recall bounded by its word lists. The density label that enters the dataset is
the human one from annotation/guideline.md. Never substitute one for the other.
"""

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

from src.preprocess.cs_screen import bucket, classify
from src.preprocess.langfilter import detect as detect_lang
from src.preprocess.textnorm import (
    anonymize, classify_row, collapse_repeats, n_tokens, norm_key,
    token_key, utf8_stdout,
)

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
INTERIM = ROOT / "data" / "interim"

# A normalized text appearing under this many distinct videos is copypasta,
# not coincidence.
COPYPASTA_VIDEOS = 3


def load_raw(files):
    """Read raw JSONL, anonymize, drop the author field. Author names never
    leave this function."""
    out, seen_ids = [], set()
    dup_ids = 0
    for fp in files:
        with open(fp, encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                c = json.loads(line)
                cid = c.get("comment_id")
                if cid in seen_ids:
                    dup_ids += 1
                    continue
                seen_ids.add(cid)
                text = collapse_repeats(anonymize(c.get("text", "")))
                out.append({
                    "comment_id": cid,
                    "video_id": c.get("video_id"),
                    "source_file": fp.name,
                    "text": text,
                    "like_count": c.get("like_count", 0),
                    "published_at": c.get("published_at"),
                })
    return out, dup_ids


def find_copypasta(rows):
    """Normalized texts posted under >= COPYPASTA_VIDEOS distinct videos."""
    vids = defaultdict(set)
    for r in rows:
        vids[norm_key(r["text"])].add(r["video_id"])
    return {k for k, v in vids.items() if len(v) >= COPYPASTA_VIDEOS}


def build_report(rows, excluded, dropped, kept, romanized):
    lines = []
    w = lines.append
    total_dropped = sum(dropped.values())
    buckets = Counter(r["screen_bucket"] for r in kept)
    eligible = Counter(r["screen_bucket"] for r in kept if r["density_eligible"])

    w("# Corpus build report")
    w("")
    w("Generated by `src/preprocess/build_corpus.py`. Regenerate rather than "
      "editing by hand.")
    w("")
    w("## Input")
    w("")
    w("| Source file | Comments |")
    w("|---|---|")
    for k, v in sorted(Counter(r["source_file"] for r in rows).items()):
        w("| `{}` | {} |".format(k, v))
    w("| **total unique ids** | **{}** |".format(len(rows)))
    w("")
    if excluded:
        w("Excluded sources: {}".format(
            ", ".join("`{}`".format(e) for e in sorted(excluded))))
        w("")

    w("## Dropped")
    w("")
    w("| Reason | Count | % of input |")
    w("|---|---|---|")
    for k, v in dropped.most_common():
        w("| {} | {} | {:.1f}% |".format(k, v, v / len(rows) * 100))
    w("| **total** | **{}** | **{:.1f}%** |".format(
        total_dropped, total_dropped / len(rows) * 100))
    w("")

    w("## Kept")
    w("")
    w("| Pool | Comments |")
    w("|---|---|")
    w("| `corpus_clean.jsonl` (annotatable) | {} |".format(len(kept)))
    w("| of which density-eligible (>= 5 tokens) | {} |".format(
        sum(1 for r in kept if r["density_eligible"])))
    w("| `corpus_romanized.jsonl` (held aside) | {} |".format(len(romanized)))
    w("")

    w("## Screen buckets in the clean pool")
    w("")
    w("The screen is a **lower bound** and a sampling tool, not the density label.")
    w("")
    w("| Screen bucket | All | Density-eligible |")
    w("|---|---|---|")
    for b in ("mono", "low", "med", "high", "unknown"):
        w("| {} | {} | {} |".format(b, buckets[b], eligible[b]))
    w("")

    w("## Annotation budget check")
    w("")
    w("Density-eligible screened med+high available: **{}**.".format(
        eligible["med"] + eligible["high"]))
    w("H2 and H3 compare models *within* density buckets, so this is the number "
      "that limits the whole study - not the size of the clean pool.")
    w("")
    return "\n".join(lines)


def main():
    utf8_stdout()
    p = argparse.ArgumentParser()
    p.add_argument("--exclude", nargs="*", default=[],
                   help="raw filenames to skip, e.g. kids_gaming.jsonl")
    p.add_argument("--include-rejected", action="store_true",
                   help="keep sources marked REJECTED in data/sources.csv")
    args = p.parse_args()

    files = sorted(RAW.glob("*.jsonl"))
    # kids_gaming was rejected in Sprint 1 on two grounds: ~3% code-switching,
    # and a comment section written by children. reports/research_report.md Part II.
    default_excluded = set() if args.include_rejected else {"kids_gaming.jsonl"}
    excluded = default_excluded | set(args.exclude)
    files = [f for f in files if f.name not in excluded]
    if not files:
        raise SystemExit("No raw JSONL to process in data/raw/.")

    print("reading: {}".format(", ".join(f.name for f in files)))
    if excluded:
        print("excluded: {}".format(", ".join(sorted(excluded))))

    rows, dup_ids = load_raw(files)
    print("\n{} unique comment_ids ({} duplicate ids collapsed)".format(
        len(rows), dup_ids))

    copypasta = find_copypasta(rows)
    if copypasta:
        print("{} distinct texts flagged as cross-video copypasta".format(len(copypasta)))

    dropped = Counter()
    kept, romanized, otherlang = [], [], []
    seen_norm, seen_tok = set(), set()

    for r in rows:
        text = r["text"]
        status, reason = classify_row(text)
        if status == "drop":
            dropped[reason] += 1
            continue

        nk = norm_key(text)
        if nk in copypasta:
            dropped["copypasta"] += 1
            continue
        if nk in seen_norm:
            dropped["exact_duplicate"] += 1
            continue
        seen_norm.add(nk)

        tk = token_key(text)
        if tk is not None:
            if tk in seen_tok:
                dropped["reordered_duplicate"] += 1
                continue
            seen_tok.add(tk)

        # Neighbouring languages are routed aside before anything else looks at
        # the text. They are only 2.0% of the corpus, but density.py has no
        # model for them and files ~70% of them as code-switched, so they
        # concentrate in exactly the buckets this study depends on: measured on
        # the first draw they were 8.8% of `high` against 0.3% of `mono`.
        other = detect_lang(text)
        if other:
            otherlang.append({"comment_id": r["comment_id"], "video_id": r["video_id"],
                              "text": text, "language": other})
            dropped["other_language_" + other] += 1
            continue

        kk, ru, _ = classify(text)
        rec = {
            "comment_id": r["comment_id"],
            "video_id": r["video_id"],
            "source_file": r["source_file"],
            "text": text,
            "n_tokens": n_tokens(text),
            "screen_kk": kk,
            "screen_ru": ru,
            "screen_bucket": bucket(kk, ru),
            "density_eligible": status == "ok",
            "like_count": r["like_count"],
            "published_at": r["published_at"],
        }
        (romanized if status == "romanized" else kept).append(rec)

    INTERIM.mkdir(parents=True, exist_ok=True)
    clean_fp = INTERIM / "corpus_clean.jsonl"
    rom_fp = INTERIM / "corpus_romanized.jsonl"
    other_fp = INTERIM / "corpus_otherlang.jsonl"
    for fp, data in ((clean_fp, kept), (rom_fp, romanized), (other_fp, otherlang)):
        with open(fp, "w", encoding="utf-8") as f:
            for rec in data:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    report_fp = INTERIM / "corpus_report.md"
    report_fp.write_text(
        build_report(rows, excluded, dropped, kept, romanized), encoding="utf-8")
    print("routed aside as another language: {}".format(len(otherlang)))

    print("\n--- dropped ---")
    for k, v in dropped.most_common():
        print("  {:<24} {:>6}  {:>5.1f}%".format(k, v, v / len(rows) * 100))
    print("\nclean pool:           {:>6}".format(len(kept)))
    print("  density-eligible:   {:>6}".format(
        sum(1 for r in kept if r["density_eligible"])))
    print("romanized held aside: {:>6}".format(len(romanized)))

    eligible = Counter(r["screen_bucket"] for r in kept if r["density_eligible"])
    print("\nscreen buckets (density-eligible):")
    for b in ("mono", "low", "med", "high", "unknown"):
        print("  {:<8} {:>6}".format(b, eligible[b]))
    print("\n-> {}\n-> {}\n-> {}".format(clean_fp, rom_fp, report_fp))


if __name__ == "__main__":
    main()
